### ISSUE TITLE
Error 1003 when deploying for LinuxRT 64 bit (duplicated names on vi.lib)

### ISSUE THREAD

**Issue by fmussi** [ni/niveristand-fpga-addon-custom-device#125]
**Describe the bug**
I can compile engine build distribution but I've error 1003 when deploying

**To Reproduce**
1. Compile Engine Release build distribution under RT CompactRIO Target - Linux x64 target
2. Deploy a VS sysdef on a linux rt target

**Details**
Looking to the target CD folder, there's the llb and 2 folders for the VIs with duplicated names. These are:

![image](https://user-images.githubusercontent.com/8535457/123936099-28098880-d995-11eb-991a-0cbd3b674ab3.png)
each of them having these 2 files:
![image](https://user-images.githubusercontent.com/8535457/123936175-39eb2b80-d995-11eb-801b-02cb52a2a593.png)

**Please complete the following information:**
 - OS: Linux RT 64 bit
 - Release Version: latest commit (#124) 

**Additional context**
Fix is pretty easy (e.g. adding NI_Data Type lvlib to the project items and renaming conflicting items during build) but it's sort of manual and impact user productivity

**Comment by DStavilaNI** [comment]
Hey Fabio,
  
              Please make sure to have the following token added to your LabVIEW.ini file: "NI_AppBuilder_SDist_ExcludeEditTime=True". 
              
              The final build should like this (without any extra files):
                            
![image](https://user-images.githubusercontent.com/35329597/124251782-e7705300-daeb-11eb-9004-afd0624a2951.png)

This should eliminate the issue that you are facing.
Sincerely yours,
Denis

**Comment by DStavilaNI** [comment]
Assumed fixed
