### ISSUE TITLE
FPGA Addon Default Values Not Being Retained

### ISSUE THREAD

**Issue by aequitz** [ni/niveristand-fpga-addon-custom-device#155]
**Describe the bug**
Default values for the FPGA Addon custom device are not retained when re-opening VeriStand System Explorer.

**To Reproduce**
1. Open attached system definition file in VeriStand system explorer.
2. Change default value of Controller/Custom Devices/PXIe-7821R/Scalars/Scalar Outputs/DMA.Enable to 1.
3. Open the system definition file in a text editor to confirm that DMA.Enable's default value is 1.
4. Reopen the system definition file in VeriStand system explorer.
5. Navigate to the DMA.Enable signal. The default value is now shown as 0.

**Expected behavior**
I would expect the default values to be shown the next time the System Explorer is opened.

**Screenshots**
N/A

**Please complete the following information:**
 - OS: Linux x64
 - Release Version 20.6

**Additional context**
N/A

**Attachments**
[FPGA Addon Bug Files.zip](https://github.com/ni/niveristand-fpga-addon-custom-device/files/9242702/FPGA.Addon.Bug.Files.zip)

**Comment by aequitz** [comment]
Is it possible to get a new release that includes this fix?

**Comment by buckd** [comment]
@aequitz I'll try to get you one Monday.

**Comment by buckd** [comment]
@aequitz 
New release [v21.3.0](https://github.com/ni/niveristand-fpga-addon-custom-device/releases/tag/v21.3.0)
